# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           http:\/\/blog.whitecitycode.com/article/:title/
relative_permalinks: false

# Setup
title:               'WhiteCity Code'
tagline:             'official blog'
description:         'We write on development topics, functional programming and challenges we encounter and solve.'
url:                 blog.whitecitycode.com
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              WhiteCity Code
  url:               https://whitecitycode.com
  email:             hq@whitecitycode.com

# Custom vars
version:             1.0.0
